### PR TITLE
AxialPoint

### LINKED ISSUE #2: Add features and tests to `AxialPoint`
The `AxialPoint` type is currently very incomplete. It should implement all fitting traits from `cgmath` and overload many operators:

- overload many useful operators (including `Index`, required by `Array` anyway)
- implement `cgmath::{Zero, Array, MetricSpace, VectorSpace, InnerSpace}`

Everything should be done similar to [cgmath::Point2](http://bjz.github.io/cgmath/cgmath/struct.Point2.html).

Additionally multiple unit tests should be added to ensure correctness.

*Note*: this issue is similar to #1

### PR DESCRIPTION
**Pull request by FischerTo**
Fixes #2

### CODE REVIEW

**Comment by FischerTo** [comment]
closes #2

**Comment by FischerTo** [comment]
closes #2

**Comment by jonas-schievink** [comment]
Put "Fixes #2" in the PR description at the top (not in a comment), then it will automatically close #2 when merged.

**Comment by LukasKalbertodt** [comment]
Please split your test into multiple functions, as described [here](https://github.com/OsnaCS/plantex/pull/20#issuecomment-234309314)

**Pull request merged**
